apiVersion: v1
kind: Service
metadata:
  name: metanet-msa-migration-be-java
  namespace: metabank
spec:
  selector:
    app: metanet-msa-migration-be-java
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
