apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: metanet-msa-migration-fe
  namespace: metabank
  labels:
    app: metanet-msa-migration-fe
spec:
  replicas: 5
  strategy:
    blueGreen:
      activeService: metanet-msa-migration-fe-active  # 운영 중인 서비스
      previewService: metanet-msa-migration-fe-preview  # 새 버전 서비스 (테스트용)
      previewReplicaCount: 2
      autoPromotionEnabled: false  # 자동 배포 방지 (수동 프로모션)
      autoPromotionSeconds: 60
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: metanet-msa-migration-fe
  template:
    metadata:
      labels:
        app: metanet-msa-migration-fe
    spec:
      containers:
        - name: metanet-msa-migration-fe
          image: yubyeongmin/frontend:bluegreen  # 초기 이미지
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: metanet-msa-migration-fe
          volumeMounts:
            - name: tls-secret
              mountPath: /etc/nginx/ssl
              readOnly: true
      volumes:
        - name: tls-secret
          secret:
            secretName: istio-ingressgateway-certs
