apiVersion: v1
kind: Service
metadata:
  name: metanet-msa-migration-fe
  namespace: metabank
spec:
  selector:
    app: metanet-msa-migration-fe
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
