apiVersion: apps/v1
kind: Deployment
metadata:
  name: metanet-msa-migration-quiz-reward
  namespace: metabank
  labels:
    app: metanet-msa-migration-quiz-reward
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: metanet-msa-migration-quiz-reward
  template:
    metadata:
      labels:
        app: metanet-msa-migration-quiz-reward
    spec:
      containers:
        - name: metanet-msa-migration-quiz-reward
          image: ykim73094/metanet-msa-migration-quiz-reward:1739173998
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "8080"
          envFrom:
          - configMapRef:
              name: metanet-msa-migration-quiz-reward-config
          - secretRef:
              name: metanet-msa-migration-quiz-reward-secrets
          resources:
            requests:
              cpu: "150m"  # 0.1 vCPU (기본적으로 낮게 설정)
            limits:
              cpu: "150m"  # 0.5 vCPU (최대 사용량 제한)
