apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: metanet-msa-migration-be-java-set
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - environment: dev
            namespace: metabank-dev
            project: metabank-dev
            valuesFile: values-dev.yaml
          - environment: qa
            namespace: metabank-qa
            project: metabank-qa
            valuesFile: values-qa.yaml
          - environment: prod
            namespace: metabank-prod
            project: metabank-prod
            valuesFile: values-prod.yaml
  template:
    metadata:
      name: metanet-msa-migration-be-java-{{ environment }}
    spec:
      project: "{{ project }}"
      source:
        repoURL: https://github.com/Metanet-Signal-Platoon/ArgoCD-metabank.git
        targetRevision: main
        path: argo-metanet-msa-migration-be-java-helm
        helm:
          valueFiles:
            - "values.yaml"
            - "{{ valuesFile }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ namespace }}"
      syncPolicy:
        automated:
          prune: true  # Git과 다르면 자동 삭제
          selfHeal: true  # 클러스터 변경 시 자동 복구
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
