apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metanet-msa-list-service  # ArgoCD에서 관리하는 앱 이름
  namespace: dev-metabank
spec:
  project: dev-metabank
  source:
    repoURL: https://github.com/Metanet-Signal-Platoon/ArgoCD-metabank.git  # 올바른 GitHub 리포지토리 URL
    targetRevision: dev  # dev 브랜치를 자동 Sync
    path: argo-metanet-msa-list-service-helm  # Helm 차트 경로
    helm:
      valueFiles:
      - values-qa.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-metabank
  syncPolicy:
    automated:
      prune: true     # Git과 불일치하는 리소스를 자동 삭제
      selfHeal: true  # 클러스터 변경 사항을 자동으로 복구
    syncOptions:
      - CreateNamespace=true  # 네임스페이스가 없을 경우 자동 생성
      - ApplyOutOfSyncOnly=true  # 변경된 리소스만 업데이트
      - PrunePropagationPolicy=foreground  # 관련 리소스도 삭제
      - PruneLast=true  # 마지막에 남은 불필요한 리소스 삭제
