apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "argo-metanet-msa-list-service-helm.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "argo-metanet-msa-list-service-helm.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "argo-metanet-msa-list-service-helm.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "argo-metanet-msa-list-service-helm.name" . }}
    spec:
      containers:
        - name: metanet-msa-list-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - configMapRef:
                name: {{ .Values.configMap.name }}
            - secretRef:
                name: {{ .Values.secret.name }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
  strategy:
    canary:
      steps:
        - setWeight: {{ .Values.canary.steps[0].weight }}
        - pause: {duration: {{ .Values.canary.steps[0].pause }}}
        - setWeight: {{ .Values.canary.steps[1].weight }}
        - pause: {duration: {{ .Values.canary.steps[1].pause }}}
        - setWeight: 100  # Canary 트래픽 100%로 변경 (기존 버전 제거)
