apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-config
  namespace: {{ .Release.Namespace }}
data:
  default.conf: |
    {{- range .Values.backendServices }}
    upstream {{ .name }} {
        server {{ .name }}.{{ .namespace | default $.Release.Namespace }}.svc.cluster.local:{{ .port }};
    }
    {{- end }}

    server {
        listen 80;
        
        {{- range .Values.backendServices }}
        location /{{ .name }}/ {
            proxy_pass http://{{ .name }};
        }
        {{- end }}
    }
