apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "argo-metanet-msa-migration-fe-helm.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "argo-metanet-msa-migration-fe-helm.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "argo-metanet-msa-migration-fe-helm.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "argo-metanet-msa-migration-fe-helm.name" . }}
    spec:
      containers:
        - name: metanet-msa-migration-fe
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
