apiVersion: apps/v1
kind: Deployment
metadata:
  name: metanet-msa-list-service
  namespace: metabank
  labels:
    app: metanet-msa-list-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: metanet-msa-list-service
  template:
    metadata:
      labels:
        app: metanet-msa-list-service
    spec:
      containers:
        - name: metanet-msa-list-service
          image: ykim73094/metanet-msa-list-service:1739083894
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "8080"
          envFrom:
          - configMapRef:
              name: metanet-msa-list-service
          - secretRef:
              name: metanet-msa-list-service-secrets
