apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: metanet-msa-list-service
  namespace: metabank
  labels:
    app: metanet-msa-list-service
spec:
  replicas: 5
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: metanet-msa-list-service

  strategy:
    canary:
      canaryService: metanet-msa-list-service-canary
      stableService: metanet-msa-list-service-stable
      steps:
        - setWeight: 20
        - pause:
            duration: 30
        - setWeight: 50
        - pause:
            duration: 60

  template:
    metadata:
      labels:
        app: metanet-msa-list-service
    spec:
      containers:
        - name: metanet-msa-list-service
          image: ykim73094/metanet-msa-list-service:1739083894
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "8080"
          envFrom:
            - configMapRef:
                name: metanet-msa-list-service-config
            - secretRef:
                name: metanet-msa-list-service-secrets
          resources:
            requests:
              cpu: "150m"
            limits:
              cpu: "250m"
