apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "metanet-msa-migration-be-java.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "metanet-msa-migration-be-java.name" . }}
spec:
  revisionHistoryLimit: 1
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "metanet-msa-migration-be-java.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "metanet-msa-migration-be-java.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - configMapRef:
                name: {{ .Values.configMap.name }}
            - secretRef:
                name: {{ .Values.secret.name }}
          livenessProbe: 
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
