apiVersion: v1
kind: Service
metadata:
  name: {{ include "argo-metanet-msa-migration-be-java-helm.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ include "argo-metanet-msa-migration-be-java-helm.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}
