apiVersion: v1
kind: Service
metadata:
  name: {{ include "metanet-msa-migration-be-java.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ include "metanet-msa-migration-be-java.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}
